server:
  port: 9089
  tomcat:
    max-swallow-size: 20MB
spring:
  application:
    name: simple-api-doc
  messages:
    basename: messages
    encoding: UTF-8
  datasource:
    driver-class-name: ${DB_CLASS_NAME:${dbs.${dbs.type}.driver-class-name}}
    url: ${DB_URL:${dbs.${DB_TYPE:h2}.url}}
#    url: jdbc:h2:mem:simpledb
    username: ${DB_USERNAME:${dbs.${dbs.type}.username}}
    password: ${DB_PASSWORD:${dbs.${dbs.type}.password}}
    hikari: # 连接池配置
      maximum-pool-size: ${DB_POOL_SIZE:5}
      minimum-idle: 2
      connection-test-query: select 1;
  h2:
    console:
      enabled: ${DB_H2_CONSOLE:${dbs.${dbs.type}.console:false}}
      settings:
        web-allow-others: true
  flyway:
    baseline-on-migrate: true
    out-of-order: true
    placeholder-prefix: "${"
    table: flyway_schema_history
    locations: classpath:db/${DB_TYPE:h2}/migration
  jackson: #jackson配置
    deserialization:
      ACCEPT_SINGLE_VALUE_AS_ARRAY: true
      FAIL_ON_UNKNOWN_PROPERTIES: false
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      INDENT_OUTPUT: false
    mapper:
      USE_WRAPPER_NAME_AS_PROPERTY_NAME: true
      PROPAGATE_TRANSIENT_MARKER: true
    default-property-inclusion: non_null
    time-zone: GMT+8
mybatis-plus:
  global-config:
    db-config:
      table-prefix: t_
      table-underline: true
      update-strategy: always
    banner: false
logging: # 日志相关配置
  level:
    root: info
  config: classpath:logback-spring.xml
  file:
    path: ${LOG_DIR:logs/${spring.application.name}}
    name: ${logging.file.path}/${spring.application.name}.log
# 自定义database信息
simple:
  api:
    jwt-password: ${API_JWT_PASSWORD:}
    jwt-expire: ${API_JWT_EXPIRE:7}
    project-version: @project.version@
    task-enabled: ${API_TASK_ENABLED:true}
    task-pool-size: ${API_TASK_POOL_SIZE:10}
dbs:
  type: ${DB_TYPE:h2}
  h2:
    driver-class-name: org.h2.Driver
    data-dir: ${DB_DATA_DIR:~}
    url: jdbc:h2:file:${dbs.h2.data-dir}/simple-api-doc/apidoc-db;AUTO_SERVER=TRUE
    username: root
    password: 123456
  mysql:
    driver-class-name: com.mysql.cj.jdbc.Driver
    server: ${DB_MYSQL_SERVER:localhost}
    port: ${DB_MYSQL_PORT:3306}
    dbname: ${DB_MYSQL_DBNAME:api-db}
    url: jdbc:mysql://${dbs.mysql.server}:${dbs.mysql.port}/${dbs.mysql.dbname}?characterEncoding=utf8&useUnicode=true&serverTimezone=UTC
    username: root
    password: 12345678
