CREATE TABLE t_api_doc
(
    id           int GENERATED BY DEFAULT AS IDENTITY,
    project_id   int NOT NULL,
    folder_id    int,
    doc_type     varchar(255),
    doc_name     varchar(8192),
    doc_content  text,
    doc_key      varchar(2048),
    status       tinyint,
    operation_id varchar(8192),
    deprecated   bit,
    method       varchar(255),
    url          varchar(8192),
    summary      text,
    description  text,
    creator      varchar(255),
    modifier     varchar(255),
    create_date  timestamp,
    modify_date  timestamp,
    PRIMARY KEY (id)
);

CREATE TABLE t_api_doc_schema
(
    id             int GENERATED BY DEFAULT AS IDENTITY,
    doc_id         int,
    body_type      varchar(255),
    schema_content text,
    schema_key     varchar(4096),
    schema_name    varchar(4096),
    content_type   varchar(255),
    description    text,
    creator        varchar(255),
    modifier       varchar(255),
    create_date    timestamp,
    modify_date    timestamp,
    PRIMARY KEY (id)
);
CREATE TABLE t_api_folder
(
    id          int GENERATED BY DEFAULT AS IDENTITY,
    project_id  int NOT NULL,
    folder_name varchar(8192),
    root_flag   bit,
    status      tinyint DEFAULT 0,
    parent_id   int,
    description text,
    creator     varchar(255),
    modifier    varchar(255),
    create_date timestamp,
    modify_date timestamp,
    PRIMARY KEY (id)
);
CREATE TABLE t_api_project
(
    id           int GENERATED BY DEFAULT AS IDENTITY,
    user_name    varchar(255),
    project_code varchar(255) UNIQUE,
    project_name varchar(4096),
    status       tinyint DEFAULT 0,
    private_flag bit     DEFAULT '1',
    description  text,
    creator      varchar(255),
    modifier     varchar(255),
    create_date  timestamp,
    modify_date  timestamp,
    PRIMARY KEY (id)
);
CREATE TABLE t_api_project_info
(
    id           int GENERATED BY DEFAULT AS IDENTITY,
    project_id   varchar(255),
    folder_id    int,
    import_type  varchar(255),
    file_name    varchar(8192),
    source_type  varchar(255),
    url          varchar(8192),
    env_content  varchar(8192),
    auth_type    varchar(255),
    auth_content varchar(8192),
    version      varchar(255),
    oas_version  varchar(255),
    spec_version varchar(255),
    creator      varchar(255),
    modifier     varchar(255),
    modify_date  timestamp,
    create_date  timestamp,
    PRIMARY KEY (id)
);
CREATE TABLE t_api_project_info_detail
(
    id             int GENERATED BY DEFAULT AS IDENTITY,
    project_id     varchar(255),
    info_id        int,
    body_type      varchar(255),
    schema_content text,
    schema_name    varchar(4096),
    schema_key     varchar(4096),
    content_type   varchar(255),
    description    text,
    creator        varchar(255),
    modifier       varchar(255),
    modify_date    timestamp,
    create_date    timestamp,
    PRIMARY KEY (id)
);

CREATE TABLE t_api_project_share
(
    id             int GENERATED BY DEFAULT AS IDENTITY,
    project_id     int,
    share_id       varchar(32) NOT NULL UNIQUE,
    share_name     varchar(255),
    export_enabled bit,
    debug_enabled  bit,
    env_content    varchar(8192),
    expire_date    timestamp,
    share_password varchar(255),
    status         tinyint DEFAULT 0,
    creator        varchar(255),
    modifier       varchar(255),
    modify_date    timestamp,
    create_date    timestamp,
    PRIMARY KEY (id)
);
CREATE TABLE t_api_project_task
(
    id             int GENERATED BY DEFAULT AS IDENTITY,
    project_id     int,
    task_type      varchar(255),
    source_type    varchar(255),
    source_url     varchar(8192),
    schedule_rate  int,
    task_name      varchar(4096),
    to_folder      int,
    overwrite_mode int,
    auth_type      varchar(255),
    auth_content   varchar(8192),
    status         tinyint DEFAULT 0,
    exec_date      timestamp,
    creator        varchar(255),
    modifier       varchar(255),
    modify_date    timestamp,
    create_date    timestamp,
    PRIMARY KEY (id)
);
CREATE TABLE t_api_user
(
    id            int GENERATED BY DEFAULT AS IDENTITY,
    user_name     varchar(255),
    user_password varchar(255),
    status        tinyint DEFAULT 0,
    nick_name     varchar(255),
    user_email    varchar(255),
    creator       varchar(255),
    modifier      varchar(255),
    create_date   timestamp,
    modify_date   timestamp,
    PRIMARY KEY (id)
);
