CREATE TABLE t_api_project
(
    id           int GENERATED BY DEFAULT AS IDENTITY,
    user_name    varchar(255),
    project_name varchar(255),
    project_code varchar(255),
    status       tinyint,
    private_flag bit,
    description  varchar(1024),
    creator      varchar(255),
    create_date  timestamp,
    modifier     varchar(255),
    modify_date  timestamp,
    PRIMARY KEY (id)
);
CREATE TABLE t_api_project_schema
(
    id             int GENERATED BY DEFAULT AS IDENTITY,
    project_id     int,
    url            varchar(8192),
    file_name      varchar(255),
    content_type   varchar(255),
    env_content    varchar(8192),
    content_schema text,
    auth_type      varchar(255),
    auth_content   varchar(8192),
    creator        varchar(255),
    create_date    timestamp,
    modifier       varchar(255),
    modify_date    timestamp,
    PRIMARY KEY (id)
);
CREATE TABLE t_api_user
(
    id            int GENERATED BY DEFAULT AS IDENTITY,
    user_name     varchar(255),
    user_password varchar(255),
    status        int,
    user_email    varchar(2049),
    nick_name     varchar(255),
    creator       varchar(255),
    create_date   timestamp,
    modifier      varchar(255),
    modify_date   timestamp,
    PRIMARY KEY (id)
);
