CREATE TABLE t_api_group
(
    id          int GENERATED BY DEFAULT AS IDENTITY,
    group_code  varchar(255),
    group_name  varchar(1024),
    description text,
    status      tinyint DEFAULT 0,
    creator     varchar(255),
    modifier    varchar(255),
    create_date timestamp,
    modify_date timestamp,
    CONSTRAINT description
        PRIMARY KEY (id)
);
CREATE TABLE t_api_user_group
(
    id          int GENERATED BY DEFAULT AS IDENTITY,
    user_id     int,
    group_code  varchar(255),
    authorities varchar(1024),
    creator     varchar(255),
    create_date timestamp,
    PRIMARY KEY (id)
);
ALTER TABLE t_api_project
    ADD COLUMN group_code varchar(255);
