ALTER TABLE t_api_project_schema
    ADD COLUMN source_type varchar(255);
ALTER TABLE t_api_project_schema
    ADD COLUMN import_type varchar(255);

CREATE TABLE t_api_doc
(
    id           int GENERATED BY DEFAULT AS IDENTITY,
    project_id   int NOT NULL,
    folder_id    int,
    doc_type     varchar(255),
    doc_name     varchar(8192),
    doc_content  text,
    status       tinyint,
    operation_id varchar(8192),
    method       varchar(255),
    url          varchar(8192),
    summary      text,
    description  text,
    creator      varchar(255),
    modifier     varchar(255),
    create_date  timestamp,
    modify_date  timestamp,
    PRIMARY KEY (id)
);
CREATE TABLE t_api_doc_schema
(
    id             int GENERATED BY DEFAULT AS IDENTITY,
    doc_id         int,
    body_type      varchar(255),
    schema_content text,
    content_type   varchar(255),
    description    text,
    creator        varchar(255),
    modifier       varchar(255),
    create_date    timestamp,
    modify_date    timestamp,
    PRIMARY KEY (id)
);
CREATE TABLE t_api_folder
(
    id          int GENERATED BY DEFAULT AS IDENTITY,
    project_id  int NOT NULL,
    folder_name varchar(4096),
    root_flag   bit,
    status      tinyint DEFAULT 0,
    parent_id   int,
    creator     varchar(255),
    modifier    varchar(255),
    create_date timestamp,
    modify_date timestamp,
    PRIMARY KEY (id)
);
CREATE TABLE t_api_project_task
(
    id             int GENERATED BY DEFAULT AS IDENTITY,
    project_id     int,
    task_type      varchar(255),
    source_type    varchar(255),
    source_url     varchar(8192),
    schedule_rate  int,
    task_name      varchar(4096),
    to_folder      int,
    overwrite_mode int,
    auth_type      varchar(255),
    auth_content   varchar(8192),
    status         tinyint DEFAULT 0,
    exec_date      timestamp,
    creator        varchar(255),
    modifier       varchar(255),
    modify_date    timestamp,
    create_date    timestamp,
    PRIMARY KEY (id)
);
CREATE TABLE t_api_project_share
(
    id             int GENERATED BY DEFAULT AS IDENTITY,
    project_id     int,
    share_id       varchar(32) NOT NULL UNIQUE,
    share_name     varchar(255),
    export_enabled bit,
    debug_enabled  bit,
    env_content    varchar(8192),
    expire_date    timestamp,
    share_password varchar(255),
    status         tinyint DEFAULT 0,
    creator        varchar(255),
    modifier       varchar(255),
    modify_date    timestamp,
    create_date    timestamp,
    PRIMARY KEY (id)
);

