ALTER TABLE t_api_doc
    ADD COLUMN doc_version int;
CREATE TABLE t_api_doc_history
(
    id          int GENERATED BY DEFAULT AS IDENTITY,
    doc_id      int,
    doc_type    varchar(40),
    doc_name    text,
    doc_content longtext,
    doc_key     varchar(2048),
    status      tinyint,
    sort_id     int,
    description text,
    doc_version int,
    creator     varchar(255),
    create_date timestamp,
    PRIMARY KEY (id)
);
